// Invoice memo prefix checker.
//
// Invoice memos generated by generateInvoiceMemo() follow the format
// INV-TIMESTAMP-RANDOM. This module provides a pure helper that checks
// whether an arbitrary value is a string that starts with the invoice
// prefix "INV-" (case-sensitive).

/**
 * Case-sensitive prefix used for invoice memos.
 */
export const INVOICE_MEMO_PREFIX = 'INV-';

/**
 * Check whether a value is a string that starts with the invoice memo prefix.
 *
 * The check is case-sensitive and exact: only "INV-" at the start of a
 * string returns true. Non-string values, null, undefined, empty strings,
 * and strings shorter than the prefix length return false.
 *
 * @param memo - The value to inspect.
 * @returns True when memo is a string starting with "INV-", otherwise false.
 */
export const hasInvoiceMemoPrefix = (memo: unknown): boolean => {
  if (typeof memo !== 'string') {
    return false;
  }
  return memo.startsWith(INVOICE_MEMO_PREFIX);
};

export default {
  hasInvoiceMemoPrefix,
  INVOICE_MEMO_PREFIX,
};
